### PR TITLE
Add more HTTP getter methods to connection

### PR DESCRIPTION
**Pull request by anthonynovatsis**
Added methods to retrieve the status code and all headers.

### CODE REVIEW

**Comment by zsims** [comment]
:+1: :+1:. Can we upstream this?

**Comment by anthonynovatsis** [comment]
Updated PR to only expose the response status (not response headers as they are not required anymore).

Will upstream!

**Comment by zsims** [comment]
As discussed, happy with the new approach. :+1: :+1:

**Comment by anthonynovatsis** [comment]
Method already available in the development version of `websocketpp` 0.7.x-dev (method name `get_response_code`)

**Pull request merged**
